# Generated by Django 3.2.5 on 2022-06-08 18:18

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('titleId', models.CharField(max_length=25)),
                ('title', models.TextField()),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('tconst', models.CharField(max_length=25)),
                ('averageRating', models.FloatField()),
                ('numVotes', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
    ]
